=== billy7x17/SSIDemo/ssiDemo/src/main/webapp/twaver/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by dreams (LG) -->
<!--W3C Schema generated by XMLSpy v2009 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:attribute name="V1.0">
        <xs:annotation>
            <xs:documentation>目前并未使用此文档</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="setting" minOccurs="0"/>
                <xs:element ref="construction"/>
                <xs:element ref="increment"/>
                <xs:element ref="select"/>
                <xs:element ref="auth" minOccurs="0"/>
                <xs:element ref="plugin" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="setting">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="    "/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="select">
        <xs:simpleType>
            <xs:restriction base="xs:anyURI">
                <xs:enumeration value="http://localhost:8080/twaver/incrementMVC.jsp"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="plugin">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="factory"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="operate">
        <xs:complexType>
            <xs:attribute name="regular" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="[0-9]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="name" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="detail.mail"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="action" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="reg"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="increment">
        <xs:simpleType>
            <xs:restriction base="xs:anyURI">
                <xs:enumeration value="http://localhost:8080/twaver/incrementMVC.jsp"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="factory">
        <xs:complexType>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="com.neusoft.mid.topology.nj.factory.NJFactory"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="construction">
        <xs:simpleType>
            <xs:restriction base="xs:anyURI">
                <xs:enumeration value="http://localhost:8080/twaver/MainMVC.jsp"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="auth">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="operate"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== billy7x17/SSIDemo/ssiDemo/src/main/webapp/twaver/schema/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\DOCUME~1\dreams\桌面\schema\config.xsd">
    <setting>    </setting>
    <construction>        
        http://localhost:8080/twaver/MainMVC.jsp    
    </construction>
    <increment>
        http://localhost:8080/twaver/incrementMVC.jsp
    </increment>
    <select>
         http://localhost:8080/twaver/incrementMVC.jsp
    </select>
    <auth>
        <operate name="detail.mail" action="reg" regular="[0-9]+"/>
    </auth>
    <plugin>
        <factory type="com.neusoft.mid.topology.nj.factory.NJFactory"/>
    </plugin>
</config>
