=== billy7x17/SSIDemo/ssiDemo/src/main/webapp/twaver/schema/select.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by dreams (LG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.neusoft.com/mid" targetNamespace="http://www.neusoft.com/mid" elementFormDefault="qualified">
    <xs:include schemaLocation="base.xsd"/>
    <xs:element name="select">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alerm" type="alermType" maxOccurs="unbounded"/>
                <xs:element name="propertyGroup" type="propertyGroupType" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>详细信息的分组</xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="name">
                <xs:annotation>
                    <xs:documentation>名称</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="propertyGroupType">
        <xs:sequence>
            <xs:element name="property" type="propertyType" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>文本内容为实际数值</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
</xs:schema>

=== billy7x17/SSIDemo/ssiDemo/src/main/webapp/twaver/schema/select.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2009 (http://www.altova.com)-->
<select xsi:schemaLocation="http://www.neusoft.com/mid select.xsd" xmlns="http://www.neusoft.com/mid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <alerm seq="001" level="CLEARED" count="1">
        <property name="objectID" value="objectID4" desc="对象标识"/>
        <property name="alarmGrade" value="alarmGrade4" desc="告警级别"/>
        <property name="alarmID" value="alarmID4" desc="告警ID"/>
        <property name="alarmTitle" value="alarmTitle4" desc="告警标题"/>
        <property name="alarmType" value="alarmType4" desc="告警分类"/>
        <property name="count" value="4" desc="重复次数"/>
        <property name="alarmTime" value="alarmTime4" desc="最后发生时间"/>
        <property name="firstAlarmTime" value="firstAlarmTime4" desc="首次发生时间"/>
        <property name="alarmContent" value="alarmContent4" desc="告警内容"/>
    </alerm>
    <propertyGroup name="设备信息1">
        <property name="信息名称1" type="input" value="v001"/>
        <property name="信息名称2" type="input" value="v002"/>
        <property name="信息名称3" type="input" value="v003"/>
    </propertyGroup>
    <propertyGroup name="设备信息2">
        <property name="信息名称1" type="input" value="v001"/>
        <property name="信息名称2" type="input" value="v002"/>
        <property name="信息名称3" type="input" value="v003"/>
    </propertyGroup>
    <propertyGroup name="设备信息3">
        <property name="信息名称1" type="input" value="v001"/>
        <property name="信息名称2" type="input" value="v002"/>
        <property name="信息名称3" type="input" value="v003"/>
    </propertyGroup>
</select>
